
services:
  # Django バックエンドサービス
  backend:
    build:
      context: ./backend # backendディレクトリのDockerfileを使用
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 # Djangoサーバーを起動
    volumes:
      - ./backend:/app # ホストのbackendディレクトリをコンテナの/appにマウント
    ports:
      - "8000:8000" # ホストの8000番ポートをコンテナの8000番ポートにマッピング
    env_file:
      - .env.dev # 環境変数を設定
    depends_on:
      db:
        condition: service_healthy # <-- ここを修正
    networks:
      - app_network

  # PostgreSQL データベースサービス
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    networks:
      - app_network
    healthcheck: # <-- このヘルスチェックを追加！
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s # 起動後10秒はチェックを待つ

  # React Native フロントエンドサービス
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: pnpm expo start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "8081:8081"
    networks:
      - app_network
    environment:
      REACT_APP_API_URL: http://backend:8000

networks:
  app_network:
    driver: bridge

volumes:
  pg_data: