# Generated by Django 5.2.4 on 2025-07-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RamenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=50)),
                ('ordered_item', models.CharField(blank=True, max_length=100, null=True)),
                ('noodle_hardness', models.CharField(blank=True, max_length=30, null=True)),
                ('toppings', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('visited_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
