# Generated by Django 4.2.23 on 2025-07-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IkitaiStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='ユーザーの現在地の緯度')),
                ('longitude', models.FloatField(help_text='ユーザーの現在地の経度')),
                ('expires_at', models.DateTimeField(help_text='このステータスが失効する日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '保留中'), ('APPROVED', '承認済み'), ('DENIED', '拒否済み')], default='PENDING', max_length=10, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ユーザー関係',
                'verbose_name_plural': 'ユーザー関係',
                'db_table': 'user_relationships',
                'ordering': ['-created_at'],
            },
        ),
    ]
